# Generated by Django 5.2.8 on 2025-11-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_day',
        ),
        migrations.AlterField(
            model_name='author',
            name='biografi',
            field=models.TextField(blank=True),
        ),
    ]
