# Generated by Django 5.2.8 on 2025-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_published_day_alter_author_biografi'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kholase',
            field=models.TextField(default='kh'),
        ),
    ]
